# nome da ação
name: Build Java Project

# gatilho da ação
on:
  push:
    branches: [ master ]

# execução da ação
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Configure Java
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Build Project
        run: mvn clean install
