spring:

  application:
    name: EventClean

  datasource:
    url: jdbc:h2:mem:testdb
    username: admin
    password: admin
    driver-class-name: org.h2.Driver

  h2:
    console:
      enable: true
      path: /h2-console

  jpa:
    show-sql: true

  flyway:
    enabled: true

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui
